name: playermover
main: io.github.kosmx.playermover.spigot.SpigotPlugin
version: 3.1415
author: KosmX

softdepend:
  - CommandAPI

commands:
  moveplayer:
    description: Move a player to another server
    usage: /moveplayer [player] <server>
